<!DOCTYPE html>
<html lang="si">

<head>
    <meta charset="UTF-8">
    <title>Institution List - {{ $zeo->name }}</title>

    <style>
        body {
            font-family: dejavusans, sans-serif;
            font-size: 12px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
        }

        th {
            background-color: #075f75;
            color: #fff;
            padding: 6px;
            font-size: 12px;
            border: 1px solid #ddd;
        }

        td {
            padding: 6px;
            font-size: 11px;
            border: 1px solid #ddd;
            vertical-align: top;
        }

        .sub-title {
            font-size: 14px;
            margin-bottom: 10px;
        }

        tr {
            page-break-inside: avoid;
        }

        @page {
            header: page-header;
            footer: page-footer;
        }
    </style>
</head>

<body>

    {{-- ================= HEADER ================= --}}
    <htmlpageheader name="page-header">
        <div style="text-align:center; font-size:10px;">
            {{ \Illuminate\Support\Str::title($zeo->name) }} – ZEO Institution / School List
        </div>
    </htmlpageheader>

    <div class="sub-title">
        <strong>{{ $zeo->name }}</strong><br>
        {{ $zeo->address ?? '-' }}
    </div>

    @php $rowNo = 1; @endphp

    {{-- ================= DATA ================= --}}
    @forelse ($institutionChunks as $chunk)

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Census No.</th>
                <th>Name & Address</th>
                <th>Contact</th>
                <th>Category</th>
                <th>Division</th>
                <th>Type</th>
            </tr>
        </thead>

        <tbody>
            @foreach ($chunk as $institution)
            <tr>
                <td style="text-align:center;">{{ $rowNo++ }}</td>

                <td style="text-align:center;">
                    {{ str_pad($institution->census_no, 5, '0', STR_PAD_LEFT) }}
                </td>

                <td>
                    <strong>{{ $institution->name ?? '-' }}</strong><br>
                    {{ $institution->address ?? '-' }}
                </td>

                <td>
                    {{ $institution->phone ?? '-' }}
                </td>

                <td>
                    {{ $institution->institutionCategory->institution_category_name ?? '-' }}
                </td>

                <td>
                    {{ $institution->divisionalEducationOffice->short_name ?? '-' }}
                </td>

                <td style="text-align:center;">
                    {{ $institution->institutionType->institution_types_name ?? '-' }}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    @if (! $loop->last)
    <pagebreak />
    @endif

    @empty
    <table>
        <tr>
            <td colspan="7" style="text-align:center;">
                No institutions available.
            </td>
        </tr>
    </table>
    @endforelse

    {{-- ================= FOOTER ================= --}}
    <htmlpagefooter name="page-footer">
        <div style="
        width:100%;
        border-top:1px solid #ccc;
        padding-top:6px;
        font-size:10px;
        color:#555;
        display:table;
    ">
            <div style="display:table-cell;text-align:left;">
                Generated by: {{ $userNic }}
            </div>

            <div style="display:table-cell;text-align:center;">
                Page {PAGENO} of {nbpg}
            </div>

            <div style="display:table-cell;text-align:right;">
                {{ now()->format('Y-m-d H:i') }}
            </div>
        </div>
    </htmlpagefooter>

</body>

</html>