<!DOCTYPE html>
<html lang="si">

<head>
    <meta charset="UTF-8">
    <title>Staff List - {{ $zeo->name }}</title>

    <style>
        body {
            font-family: dejavusans, sans-serif;
            font-size: 12px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
        }

        th {
            background-color: #075f75;
            color: #fff;
            padding: 6px;
            font-size: 12px;
            border: 1px solid #ddd;
        }

        td {
            padding: 6px;
            font-size: 11px;
            border: 1px solid #ddd;
            vertical-align: top;
        }

        .sub-title {
            font-size: 14px;
            margin-bottom: 10px;
        }

        tr {
            page-break-inside: avoid;
        }

        @page {
            header: page-header;
            footer: page-footer;
        }
    </style>
</head>

<body>

    {{-- ================= HEADER ================= --}}
    <htmlpageheader name="page-header">
        <div style="text-align:center; font-size:10px;">
            {{ \Illuminate\Support\Str::title($zeo->name) }} – ZEO Staff List
        </div>
    </htmlpageheader>

    <div class="sub-title">
        <strong>{{ $zeo->name }} Staff List</strong><br>
        {{ $zeo->address ?? '-' }}
    </div>

    @php $rowNo = 1; @endphp

    {{-- ================= DATA ================= --}}
    @forelse ($staffChunks as $chunk)

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Full Name</th>
                <th>NIC</th>
                <th>Position / Service</th>
                <th>Contact</th>
                <th>Appoint Date</th>
                <th>Service Duration</th>
            </tr>
        </thead>

        <tbody>
            @foreach ($chunk as $member)
            @php
            $appointDate = $member->appoint_date
            ? \Carbon\Carbon::parse($member->appoint_date)
            : null;

            $duration = $appointDate
            ? $appointDate->diff(now())->format('%y years %m months')
            : '-';
            @endphp

            <tr>
                <td style="text-align:center;">{{ $rowNo++ }}</td>

                <td>
                    {{ $member->employee->title->title_name ?? '' }}
                    {{ $member->employee->full_name ?? '-' }}
                </td>

                <td>
                    {{ $member->employee->nic ?? '-' }}
                </td>

                <td>
                    {{ $member->position->position_name ?? '-' }}<br>
                    {{ $member->service->service_name ?? '-' }}
                    {{ $member->rank->rank_name ?? '' }}
                </td>

                <td>
                    {{ $member->employee->phone ?? '-' }}
                </td>

                <td style="text-align:center;">
                    {{ $appointDate ? $appointDate->format('Y-m-d') : '-' }}
                </td>

                <td style="text-align:center;">
                    {{ $duration }}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    @if (! $loop->last)
    <pagebreak />
    @endif

    @empty
    <table>
        <tr>
            <td colspan="6" style="text-align:center;">
                No staff available.
            </td>
        </tr>
    </table>
    @endforelse

    {{-- ================= FOOTER ================= --}}
    <htmlpagefooter name="page-footer">
        <div style="
        width:100%;
        border-top:1px solid #ccc;
        padding-top:6px;
        font-size:10px;
        color:#555;
        display:table;
    ">
            <div style="display:table-cell;text-align:left;">
                Generated by: {{ $userNic }}
            </div>

            <div style="display:table-cell;text-align:center;">
                Page {PAGENO} of {nbpg}
            </div>

            <div style="display:table-cell;text-align:right;">
                {{ now()->format('Y-m-d H:i') }}
            </div>
        </div>
    </htmlpagefooter>

</body>

</html>